# Generated by Django 6.0 on 2025-12-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FULLNAME', models.CharField(max_length=255)),
                ('EMAIL', models.EmailField(max_length=254, unique=True)),
                ('COMPANY_NAME', models.CharField(max_length=255)),
                ('PASSWORD', models.CharField(max_length=255)),
                ('REQ_DATE', models.DateTimeField(db_column='REQ_DATE')),
                ('STATUS', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'AccountRequest',
                'managed': False,
            },
        ),
    ]
