# Generated by Django 6.0 on 2025-12-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountrequest',
            table='accountrequest',
        ),
    ]
