# Generated by Django 6.0 on 2025-12-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome da Empresa/Cliente')),
                ('contact_email', models.EmailField(default='no_informed', max_length=255, verbose_name='E-mail de Contato')),
                ('contract_status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], default='ACTIVE', max_length=10, verbose_name='Status do Contrato')),
            ],
            options={
                'verbose_name': 'Empresa Cliente',
                'verbose_name_plural': 'Empresas Clientes',
                'ordering': ['name'],
            },
        ),
    ]
